### ISSUE TITLE
not working in swarm mode

### ISSUE THREAD

**Issue by Akshatha-97** [djmaze/swarm-tcp-proxy#1]
Hi there,
Appreciate your work and help needed on implementing this project in docker swarm mode.
My service name is abc listening on port 80. 

Error(s) found in configuration file : /usr/local/etc/haproxy/haproxy.cfg
Exiting Master process...
Current worker 14 exited with code 143
All workers exited. Exiting... (143) 

How do I go about it?
[error.txt](https://github.com/djmaze/swarm-tcp-proxy/files/3756295/error.txt)

**Comment by djmaze** [comment]
Sorry, it seems the image in the registry was not up-to-date. I just pushed a new build. Could you try again?

I'll probably set up automatic builds in order to prevent such problems in the future.
